"""Add unique constraint to author, source, tag tables

Revision ID: 0173e04cc443
Revises: 52db0be31ea3
Create Date: 2024-03-18 23:15:54.656352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0173e04cc443'
down_revision: Union[str, None] = '52db0be31ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['fullname'])
    op.create_unique_constraint(None, 'sources', ['name'])
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'sources', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
