"""Add column quote

Revision ID: 52db0be31ea3
Revises: ba481a184ad5
Create Date: 2024-03-18 22:37:32.223313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52db0be31ea3'
down_revision: Union[str, None] = 'ba481a184ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('quote', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'quote')
    # ### end Alembic commands ###
