"""Add ondelete CASCADE to tags_a
nd_quotes foreign keys

Revision ID: 59cdf6c10267
Revises: 9e5aa0356ac2
Create Date: 2024-03-19 14:31:31.165671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cdf6c10267'
down_revision: Union[str, None] = '9e5aa0356ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_and_quotes_tags_id_fkey', 'tags_and_quotes', type_='foreignkey')
    op.drop_constraint('tags_and_quotes_quote_id_fkey', 'tags_and_quotes', type_='foreignkey')
    op.create_foreign_key(None, 'tags_and_quotes', 'tags', ['tags_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_and_quotes', 'quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_and_quotes', type_='foreignkey')
    op.drop_constraint(None, 'tags_and_quotes', type_='foreignkey')
    op.create_foreign_key('tags_and_quotes_quote_id_fkey', 'tags_and_quotes', 'quotes', ['quote_id'], ['id'])
    op.create_foreign_key('tags_and_quotes_tags_id_fkey', 'tags_and_quotes', 'tags', ['tags_id'], ['id'])
    # ### end Alembic commands ###
