"""Change lengt

Revision ID: 62560c84c347
Revises: 59cdf6c10267
Create Date: 2024-03-19 14:44:04.177667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62560c84c347'
down_revision: Union[str, None] = '59cdf6c10267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'fullname',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=800),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'name',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('authors', 'fullname',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
