"""Fix source collumn in quotes

Revision ID: 91a43eeba34b
Revises: 0173e04cc443
Create Date: 2024-03-19 01:08:43.425998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a43eeba34b'
down_revision: Union[str, None] = '0173e04cc443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotes_source_id_fkey', 'quotes', type_='foreignkey')
    op.create_foreign_key(None, 'quotes', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.create_foreign_key('quotes_source_id_fkey', 'quotes', 'authors', ['source_id'], ['id'])
    # ### end Alembic commands ###
