"""Remove all back foreign key

Revision ID: 9e5aa0356ac2
Revises: 54c48a9af0b9
Create Date: 2024-03-19 02:08:12.161580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5aa0356ac2'
down_revision: Union[str, None] = '54c48a9af0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
