"""Create main 5 colums

Revision ID: ba481a184ad5
Revises: 0d8feff407c8
Create Date: 2024-03-18 22:33:33.573171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba481a184ad5'
down_revision: Union[str, None] = '0d8feff407c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_and_quotes',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('quote_id', 'tags_id')
    )
    op.drop_table('tagsandquotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagsandquotes',
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='tagsandquotes_author_id_fkey'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='tagsandquotes_quote_id_fkey'),
    sa.PrimaryKeyConstraint('quote_id', 'author_id', name='tagsandquotes_pkey')
    )
    op.drop_table('tags_and_quotes')
    # ### end Alembic commands ###
